### ISSUE TITLE
Add smooth scrolling effect on topMenu button

### ISSUE THREAD

**Issue by 0xh34rtl3ss** [meran0/TravelBuddy#68]
@nurqhaisara , @aniafiqah , @deobiz13 

just tambah ni dalam css :
```css
html {
  scroll-behavior: smooth;
}
```
